"""initial migration

Revision ID: bfc24e0b2ad3
Revises: 
Create Date: 2023-12-27 14:39:46.908915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfc24e0b2ad3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course', sa.String(length=128), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=False),
    sa.Column('chapter', sa.String(length=128), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('externalId', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('externalId', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('externalId', sa.String(length=36), nullable=False),
    sa.Column('exam_template_id', sa.Integer(), nullable=False),
    sa.Column('student_email', sa.String(length=100), nullable=False),
    sa.Column('total_grade', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_template_id'], ['exam_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_template_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('perfect_answer', sa.Text(), nullable=False),
    sa.Column('evaluation_criteria', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exam_template_id'], ['exam_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grading_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_template_id', sa.Integer(), nullable=False),
    sa.Column('criteria', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['question_template_id'], ['question_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_template_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('question_template_id', sa.Integer(), nullable=False),
    sa.Column('student_answer', sa.Text(), nullable=True),
    sa.Column('ai_grade', sa.Float(), nullable=True),
    sa.Column('ai_grade_reason', sa.Text(), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['exam_template_id'], ['exam_template.id'], ),
    sa.ForeignKeyConstraint(['question_template_id'], ['question_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_answer')
    op.drop_table('grading_criteria')
    op.drop_table('question_template')
    op.drop_table('exam')
    op.drop_table('teacher')
    op.drop_table('student')
    op.drop_table('exam_template')
    # ### end Alembic commands ###
